name = "cms-admin-app-dev"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]

d1_databases = [
    { binding = "DB", database_name = "local-db", preview_database_id = "local-db", database_id = "local-db" }
]
